version: '3.8'

services:
  node:
    container_name: node
    build: ./node
    volumes:
      - ./node:/usr/src/app
    entrypoint: "wait-for mysql:3306 -t 40 -- bash -c 'npm install && npm run start'"
    networks:
      - node-network
    ports:
      - 3333:3333

  mysql:
    container_name: mysql
    image: mysql
    volumes: 
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - node-network
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: fullcycle

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8080:80
    networks:
      - node-network
    
networks:
  node-network:
    driver: bridge
